name: dart_pubspec_licenses_lite
description: A library to make it easy to extract OSS license information from Dart packages using pubspec.yaml without the Flutter dependency.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.3.0
  path: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
