name: dart_pubspec_licenses_lite
description: A library to make it easy to extract OSS license information from Dart packages using pubspec.yaml without the Flutter dependency.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.3

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  test_process: ^2.1.0

executables:
  dart-pubspec-licenses-lite: main
