name: dart_pubspec_licenses_lite
description: A library to make it easy to extract OSS license information from Dart packages using pubspec.yaml without the Flutter dependency.
version: 1.0.0
homepage: https://github.com/techouse/flutter_oss_licenses/tree/master/packages/dart_pubspec_licenses_lite
repository: https://github.com/techouse/flutter_oss_licenses

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.3.0
  path: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
