name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v4
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubunut-latest;pub-cache-hosted;sdk:stable;packages:dart-pubspec-licenses-lite;commands:codegen-test"
          restore-keys: |
            os:ubunut-latest;pub-cache-hosted;sdk:stable;packages:dart-pubspec-licenses-lite
            os:ubunut-latest;pub-cache-hosted;sdk:stable
            os:ubunut-latest;pub-cache-hosted
            os:ubunut-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4
      - id: install
        name: Install dependencies
        run: dart pub get
      - name: Check the formatting of one or more Dart files
        run: dart format lib test --output=none --set-exit-if-changed .
      - name: Analyze the project's Dart code
        run: dart analyze lib test --fatal-infos
      - name: Test
        run: dart test
      - name: Install coverage dependencies
        run: |
          set -e
          dart pub global activate coverage
          dart pub global activate remove_from_coverage
      - name: Collect and report coverage
        run: dart pub global run coverage:test_with_coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          verbose: true
